name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build rust-ssvm lib
      run: nix-shell --run "cargo build -v"
    - name: Test rust-ssvm
      run: nix-shell --run "cargo run --example execute_vm -v -- -f=examples/fib.wasm"
